### ISSUE TITLE
Error during installation under php 8.1.9

### ISSUE THREAD

**Issue by esaesa** [yiisoft/app-api#137]
### What steps will reproduce the problem?
`composer create-project yiisoft/app-api --stability=dev myproject`
### What is the expected result?
Successful installation
### What do you get instead?
`
Creating a "yiisoft/app-api" project at "./myproject"
Info from https://repo.packagist.org: #StandWithUkraine
Installing yiisoft/app-api (1.0.x-dev c93aab6568ce1a80e3d544331c870ba2cc20da86)
  - Downloading yiisoft/app-api (dev-master c93aab6)
  - Installing yiisoft/app-api (dev-master c93aab6): Extracting archive
Created project in C:\src\myproject
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/mime-type-detection[1.0.0, ..., 1.3.0] require php ^7.2 -> your php version (8.1.9) does not satisfy that requirement.
    - league/flysystem[2.0.0-alpha.1, ..., 2.0.0-RC1] require php ^7.2 -> your php version (8.1.9) does not satisfy that requirement.`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version     |  8.1.9 
| Operating system | Win10 64bit

**Comment by vjik** [comment]
I'm try now create projects and him success created. Used `league/mime-type-detection` 1.11.0 and `league/flysystem` 2.4.5.

Is the problem still relevant? If yes, try clear composer cache (`composer clearcache`) and try create project again.
