### ISSUE TITLE
Remove `.htaccess` or move to docs

### ISSUE THREAD

**Issue by vjik** [yiisoft/app-api#194]
Apache is not always used.

**Comment by samdark** [comment]
I think that is OK to have it. It could be easily removed and doesn't hurt being there.

**Comment by samdark** [comment]
Not that often.

**Comment by vjik** [comment]
It means, that most users have to remove `.htaccess`. Suggest make better to most users, and make it now =)

**Comment by samdark** [comment]
OK. Makes sense.
