### ISSUE TITLE
Unable to create project due to version conflicts

### ISSUE THREAD

**Issue by Vetrinus** [yiisoft/app-api#205]
### What steps will reproduce the problem?

install php 8.3-cli php8.3-dom php8.3-curl
composer create-project yiisoft/app-api --stability=dev project

### What is the expected result?

project created, docker-compose.yml exists

### What do you get instead?
Creating a "yiisoft/app-api" project at "./project"
Installing yiisoft/app-api (1.0.x-dev 788abf0d2569bec9d5df492ffecaf9a7fdcc9d44)
  - Installing yiisoft/app-api (dev-master 788abf0): Extracting archive
Created project in /home/vetrinus/PhpstormProjects/project
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yiisoft/yii-debug ^3.0@dev, found yiisoft/yii-debug[dev-dependabot/composer/symfony/var-dumper-tw-7.1.1, dev-dependabot/composer/symfony/console-tw-7.1.1, dev-db-collector-cycle, dev-middleware-dispatcher, dev-master, dev-logger, dev-mutex, dev-fix-psalm-errors, dev-dev-server, dev-psalm1, dev-php80] but it does not match the constraint.
  Problem 2
    - yiisoft/yii-debug-api dev-master requires yiisoft/yii-debug dev-master -> found yiisoft/yii-debug[dev-master] but it conflicts with your root composer.json require (^3.0@dev).
    - yiisoft/yii-debug-api 3.0.x-dev is an alias of yiisoft/yii-debug-api dev-master and thus requires it to be installed too.
    - Root composer.json requires yiisoft/yii-debug-api ^3.0@dev -> satisfiable by yiisoft/yii-debug-api[3.0.x-dev (alias of dev-master)].

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.x-dev 788abf0d2569bec9d5df492ffecaf9a7fdcc9d44
| PHP version      | 8.3
| Operating system | Ubuntu Linux 22.04

**Comment by vjik** [comment]
@Vetrinus Can you try now?

**Comment by Vetrinus** [comment]
It works now, thank you
