### ISSUE TITLE
docker-compose.yml is not exists when project is created

### ISSUE THREAD

**Issue by Vetrinus** [yiisoft/app-api#207]
### What steps will reproduce the problem?
composer create-project yiisoft/app-api --stability=dev project

### What is the expected result?
docker-compose.yml file is exists

### What do you get instead?
docker-compose.yml file is not exist
so i cant follow the readme.md

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.x-dev 4c248705979d5a6405dc57f61378b48fb165a195
| PHP version      | 8.3
| Operating system | Ubuntu 20.04

**Comment by vjik** [comment]
Duplicate #157
