### ISSUE TITLE
Psalm execution reporting errors in some config files.

### ISSUE THREAD

**Issue by tarunjangra** [yiisoft/app-api#72]
### What steps will reproduce the problem?
After installation, when you execute psalm, you will find these errors.

### What is the expected result?
It should be success after psalm execution.

### What do you get instead?
```
ERROR: UndefinedGlobalVariable - config/packages/yiisoft/csrf/web.php:34:28 - Cannot find referenced variable $params in global scope (see https://psalm.dev/127)
            'secretKey' => $params['yiisoft/csrf']['hmacToken']['secretKey'],


ERROR: UndefinedGlobalVariable - config/packages/yiisoft/csrf/web.php:35:28 - Cannot find referenced variable $params in global scope (see https://psalm.dev/127)
            'algorithm' => $params['yiisoft/csrf']['hmacToken']['algorithm'],


ERROR: UndefinedGlobalVariable - config/packages/yiisoft/csrf/web.php:36:27 - Cannot find referenced variable $params in global scope (see https://psalm.dev/127)
            'lifetime' => $params['yiisoft/csrf']['hmacToken']['lifetime'],


ERROR: InvalidScope - config/packages/yiisoft/profiler/common.php:35:13 - Invalid reference to $this in a non-class context (see https://psalm.dev/013)
            $this->enable((bool)$params['enabled']);


ERROR: InvalidScope - config/packages/yiisoft/profiler/common.php:49:13 - Invalid reference to $this in a non-class context (see https://psalm.dev/013)
            $this->enable((bool)$params['enabled']);


------------------------------
5 errors found
------------------------------

```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | yii3
| PHP version      |  7.4
| Operating system | Debian

**Comment by vjik** [comment]
All errors in directory `/config`, but psalm should analyze only directory `/src` (this specified in configuration: https://github.com/yiisoft/app-api/blob/master/psalm.xml#L10). 

I'm successfully tested master branch:
![image](https://user-images.githubusercontent.com/525501/119236817-1d600600-bb42-11eb-9d05-9bed434302d8.png)

**Comment by samdark** [comment]
Here's the current run on master: https://github.com/yiisoft/app-api/runs/2633336590

**Comment by tarunjangra** [comment]
Thanks. It does make sense.
